Repository ansible-community/ansible-bender, pull requests merged in 2019-11, with the labels that each got.

#189 Extend playbook validation: Error out if there is an unknown key in vars/ansible_bender/
  ansible_bender/conf.py
  ansible_bender/core.py
  ansible_bender/schema.py
  tests/data/full_conf_pb.yaml
  tests/data/playbook_with_unknown_keys.yaml
  tests/functional/test_cli.py
  tests/functional/test_conf.py
  tests/spellbook.py
Labels: enhancement

#190 0.8.0 release
  .packit.yaml
  CHANGELOG.md
  ansible-bender.spec
Labels: bot, gate, release-bot

#197 sanity-check: print output so we can diagnose what's wrong
  ansible_bender/api.py
  ansible_bender/builders/buildah_builder.py
  ansible_bender/conf.py
  ansible_bender/core.py
  ansible_bender/exceptions.py
  ansible_bender/schema.py
  tests/data/pb_wrong_type.yaml
  tests/integration/test_buildah.py
  tests/integration/test_conf.py
  tests/spellbook.py
  tests/unit/test_ansibla.py
Labels: gate

#199 Add timestamp to failed build images to prevent overwriting.
  README.md
  ansible_bender/api.py
  tests/functional/test_buildah.py
Labels: enhancement, gate

#202 readme: drop azure pipelines badge
  README.md
Labels: gate

#203 add missing import for clean command
  ansible_bender/cli.py
  tests/functional/test_cli.py
Labels: gate

#201 Report better on returning empty log lines
  ansible_bender/builder.py
  ansible_bender/cli.py
Labels: enhancement, gate

#206 drop rawhide: buildah is not working in there right now
  .packit.yaml
  tests/conftest.py
Labels: gate
